# autostart
exec-once=noctalia
exec-once=/usr/lib/xdg-desktop-portal
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once=wl-paste --type text --watch cliphist store 
#monitor
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:119.879,x:1920,y:60
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:144,x:0,y:0

#performance

allow_tearing=0

#workspaces
tagrule=id:1,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:2,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:3,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:4,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:5,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:6,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:7,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:8,monitor_name:HDMI-A-1,layout_name:Fair
tagrule=id:9,monitor_name:eDP-1,layout_name:Fair
# layout change
#xkb_rules_variant=colemak
#input
repeat_rate=25
numlockon=0
drag_tile_to_tile=1
sloppyfocus=1
drag_tile_small=0
syncobj_enable=0
xkb_rules_layout=pl
# mouse binds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

#keybinds


#workspaces switch

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

#move window to workspace

bind=SUPER+Shift,1,tag,1,0
bind=SUPER+Shift,2,tag,2,0
bind=SUPER+Shift,3,tag,3,0
bind=SUPER+Shift,4,tag,4,0
bind=SUPER+Shift,5,tag,5,0
bind=SUPER+Shift,6,tag,6,0
bind=SUPER+Shift,7,tag,7,0
bind=SUPER+Shift,8,tag,8,0
bind=SUPER+Shift,9,tag,9,0

# Focus window in direction
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# Move/Swap Windows in direction

bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# toggle float

bind=SUPER,f,togglefloating

# Toggle maximize screen

bind=SUPER,w,togglemaximizescreen

# Toggle fullscreen

bind=SUPER+SHIFT,w,togglefullscreen
#bind=SUPER+SHIFT,w,togglefakefullscreen

# Toggle overlay
bind=Alt,tab,toggleoverview

#kill window

bind=SUPER,q,killclient

# reload conifguration

bind=SUPER,r,reload_config

# shell binds

bind=SUPER,a,spawn,noctalia msg panel-toggle launcher
bind=SUPER,y,spawn,noctalia msg panel-toggle wallpaper
bind=SUPER,escape,spawn,noctalia msg panel-toggle session
# audio
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
#media
bind=NONE,XF86AudioPlay,spawn,noctalia msg media toggle
bind=NONE,XF86AudioNext,spawn,noctalia msg media next
bind=NONE,XF86AudioPrev,spawn,noctalia msg media previous
#brightness
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down

#screenshot
bind=NONE,Print,spawn_shell,f="$HOME/Pictures/Screenshots/$(date +%Y%m%d%H%M%S).png" && grim -o "$(mmsg get focusing-client | jq -r '.monitor')" "$f" && notify-send -i "$f" "Screenshot saved"
bind=SHIFT,Print,spawn_shell,f="$HOME/Pictures/Screenshots/$(date +%Y%m%d%H%M%S).png" && g=$(slurp -d) && [ -n "$g" ] && grim -g "$g" "$f" && wl-copy < "$f" && notify-send -i "$f" "Screenshot saved and copied to clipboard"
#app binds

bind=SUPER,s,spawn,foot -e tmux
bind=SUPER,v,spawn,zeditor
bind=SUPER,n,spawn,foot -e nvim
bind=SUPER,m,spawn,foot -e nvim new
bind=SUPER,e,spawn,foot -e yazi
bind=SUPER,b,spawn,firefox
bind=SUPER,t,spawn,foot
# visuals
source=~/.config/mango/visual.conf
cursor_size=24
cursor_theme=Future-dark-cursors
source=/home/kuba/.config/mango/noctalia.conf
