# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x15131bff
bordercolor = 0x685b88ff
dropcolor = 0x9b8bc180
splitcolor = 0x5d507cff
focuscolor = 0x9b8bc1ff
maximizescreencolor = 0x7866a3ff
urgentcolor = 0xb87a87ff
scratchpadcolor = 0x5d507cff
globalcolor = 0x3f2a70ff
overlaycolor = 0x241a3dff
