shadows=1
shadows_size = 1
shadows_blur=1
shadows_position_y = -1 #important value 
shadows_position_x = -21 #important value
border_radius=0
blur=0
animations=1
animation_duration_open=100
animation_duration_close=80
animation_duration_tag=100
animation_duration_move=80
gappih=2
borderpx=1
